### ISSUE TITLE
https://zangendeutsch.de Zeitüberschreitung

### ISSUE THREAD

**Issue by Slein4273** [philipp-schuetz/zangendeutsch.de#37]
Momentan ist https://zangendeutsch.de nicht aufrufbar, man bekommt immer ein Timeout.
Meine Browser/ Addons und Netzwerkverbindung/ DNS habe ich schon überprüft.

**Comment by philipp-schuetz** [comment]
Vielen Dank für den Hinweis, sobald die neuen DNS Einstellungen angekommen sind, sollte die Seite wieder erreichbar sein.
